services:
  # Прокси-сервер, который откроет сайт и n8n по домену
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  frontend:
    build: .
    restart: always
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=vmi3258336.contaboserver.net
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://vmi3258336.contaboserver.net/webhook/check_hw
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data: